services:
  discord-bellboy-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bellboy-bot
    restart: unless-stopped
    environment:
      # Discord bot configuration
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - AUTO_JOIN_BUSIEST=${AUTO_JOIN_BUSIEST:-true}
      - AUTO_LEAVE_EMPTY=${AUTO_LEAVE_EMPTY:-true}
      # TTS configuration
      - TTS_PROVIDER=${TTS_PROVIDER:-coqui}
      # New Relic monitoring
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY:-}
      - NEW_RELIC_APP_NAME=${NEW_RELIC_APP_NAME:-Discord-Bellboy-Bot}
      - NEW_RELIC_ENVIRONMENT=${NEW_RELIC_ENVIRONMENT:-production}
      - NEW_RELIC_CONFIG_FILE=/app/newrelic.ini
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
      - ./tts-config.yaml:/app/tts-config.yaml:ro
      - tts-cache:/app/assets
    networks:
      - bellboy-network

networks:
  bellboy-network:
    driver: bridge

# Optional: Add volumes for persistent storage
volumes:
  logs:
    driver: local
  tts-cache:
    driver: local
